default_language_version:
    python: python3.9 

repos:
-  repo: https://github.com/pre-commit/mirrors-mypy
   rev: v0.812
   hooks:
   - id: mypy
     name: mypy
     entry: mypy --config-file kz159_utils/setup.cfg
